### ISSUE TITLE
Bring back Playlist covers

### ISSUE THREAD

**Issue by evkaw** [Tetrax-10/Nord-Spotify#46]
How would I go about having playlist covers while using this theme? It used to work but now for some reason I can't find how to

**Comment by Tetrax-10** [comment]
Send me screenshot. Playlist covers are there

![image](https://github.com/Tetrax-10/Nord-Spotify/assets/75513645/26ab4910-fdaa-4052-8a42-0a4a60bb8802)

**Comment by evkaw** [comment]
i mean how spotify does it normally, without the banner feature

**Comment by Tetrax-10** [comment]
I see. One thing do you have "show banners" features enabled or disabled?

**Comment by evkaw** [comment]
i have it disabled

**Comment by Tetrax-10** [comment]
Done 🎉.

**Comment by evkaw** [comment]
oh wow that was quick, thank you so much. also, would you know anything
about how nord dynamic works? i remember it working as it changes with
every song but not anymore, it just stays the same color as the playlist

**Comment by Tetrax-10** [comment]
Make sure this feature is enabled and check again. If still doesnt work then try to reset Nord settings and check (backup your settings).

If the above things dont work then please create a separate issue instead of continuing it here.

![image](https://github.com/Tetrax-10/Nord-Spotify/assets/75513645/29e32683-c85a-4e15-8741-88f3a81d98c7)

**Comment by evkaw** [comment]
thank you that worked, i thought i had it on
