### ISSUE TITLE
How to enable new UI

### ISSUE THREAD

**Issue by The-Unknown-Programming-Student** [Tetrax-10/Nord-Spotify#5]
![Screenshot_20221112_004649](https://user-images.githubusercontent.com/116381063/201414440-6972fdaf-1df7-4b17-8e5d-f6cf70ed3c91.png)
There is no search bar and home button after installation like the search bar shown in photos.

Btw
I like your musical taste.
I like Vikram Too.
Arambikkalama?😂

**Comment by Tetrax-10** [comment]
Run `spicetify config experimental_features 1` in powershell
and `spicetify apply` in powershell.
then open experimental features menu and search `new home`, choose `enable center` option.
relaunch spotify
![image](https://user-images.githubusercontent.com/75513645/201473400-4319b3e5-fcf2-4eba-9fa0-334cac9569ae.png)

![image](https://user-images.githubusercontent.com/75513645/201473342-eb6c68e0-51e9-4746-9294-a0475fb1db90.png)

run this [windows script](https://github.com/Tetrax-10/Nord-Spotify#windows-powershell-1) to install nord spotify without any errors. because i can see some errors from your pic

> Btw I like your musical taste. I like Vikram Too. Arambikkalama?😂
Thank you❤️ Arambikkalam 😂. Tamil ahh?

**Comment by The-Unknown-Programming-Student** [comment]
> 

It is working now. Thanks for helping out.
Btw Tamil than broo😂❤️‍🔥

**Comment by Tetrax-10** [comment]
>  When i connected my laptop to my monitor the the title bar seems to be a little bigger than the options below.

Feel free to send be a screenshot

> Btw Tamil than broo😂❤️‍🔥
❤️

**Comment by The-Unknown-Programming-Student** [comment]
![image](https://user-images.githubusercontent.com/116381063/202314140-ff95c885-e26e-4f14-aba1-e77aa0c80157.png)

**Comment by Tetrax-10** [comment]
What page ?
Spotify and Spicetify ?
offline or auto update version ?
