### ISSUE TITLE
Why does it look like this? It was good before but now i gotta scroll a page down to see the playlist

### ISSUE THREAD

**Issue by tsimon05** [Tetrax-10/Nord-Spotify#9]
![image](https://user-images.githubusercontent.com/68283261/202236308-47f08077-f8e6-4531-a855-32391db8c9fe.png)

**Comment by Tetrax-10** [comment]
is this happening for this song or for all the songs?
how did you install the theme marketplace or manual?

**Comment by tsimon05** [comment]
installed it on marketplace and no matter what song I play it will look like this

**Comment by Tetrax-10** [comment]
send your config

**Comment by darkvoilet** [comment]
I'm having the same issue, but it has been happening ever since i'v install the theme (via marketplace).
I tried installing the theme again from the github but nothing.

@Tetrax-10 
> send your config

This is my config:
`Settings
prefs_path                    /home/betzalel-maor/.config/spotify/prefs
color_scheme                  Spotify
spotify_launch_flags          
check_spicetify_upgrade       0
spotify_path                  /usr/share/spotify/
current_theme                 Nord-Spotify
inject_css                    1
replace_colors                1
overwrite_assets              1

Preprocesses
remove_rtl_rule               1
expose_apis                   1
disable_upgrade_check         1
disable_sentry                1
disable_ui_logging            1

AdditionalFeatures
experimental_features         1
extensions                    injectNord.js
custom_apps                   marketplace
sidebar_config                1
home_config                   1

Backup
version                       1.1.84.716.gc5f8b819
with                          2.14.1`

![image](https://user-images.githubusercontent.com/95619567/202869798-185ba4c5-d727-4bb3-ac80-51f6e8108c13.png)


![Screenshot from 2022-11-19 22-06-13](https://user-images.githubusercontent.com/95619567/202869434-7bb645d6-b32c-4bbf-a12b-bcd9d7fdf70b.png)

**Comment by Tetrax-10** [comment]
Currently this theme doent support linux. I will add support in upcomming updates

**Comment by LouisUwU** [comment]
> This theme doent support linux. Sorry 😥

I have exactly the same issue but on Windows 11, is it normal ?

**Comment by Tetrax-10** [comment]
> > This theme doent support linux. Sorry 😥
> 
> I have exactly the same issue but on Windows 11, is it normal ?

No update Spotify and Spicetify to the latest version.

Currently Nord Spotify supports Spotify 1.1.98 and Spicetify 2.14.1 also update marketplace if you have it installed

**Comment by NullChips** [comment]
Same issue on Windows. Latest Spotify version and Spicetify 2.14.1, theme installed from the Marketplace.

Banner takes up the entire screen until scrolling down, config and screenshots below. 

Not entirely sure if this is the expected behaviour or not, if it is then an option to disable this in settings would be great as it's the only thing letting down a really good theme.

Config:
`[Preprocesses]
expose_apis           = 1
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1

[AdditionalOptions]
home_config           = 1
experimental_features = 1
custom_apps           = marketplace|name-that-tune
sidebar_config        = 1
extensions            = 

[Patch]

[Setting]
spotify_launch_flags    = 
spotify_path            = C:\Users\Tom\AppData\Roaming\Spotify
replace_colors          = 1
overwrite_assets        = 0
check_spicetify_upgrade = 0
prefs_path              = C:\Users\Tom\AppData\Roaming\Spotify\prefs
inject_css              = 1
current_theme           = marketplace
color_scheme            = 

; DO NOT CHANGE!
[Backup]
version = 1.1.98.691.gf759311c
with    = 2.14.1
`

![image](https://user-images.githubusercontent.com/13980185/203426542-4304b9a3-20c2-4cf2-b959-9d806909829c.png)

**Comment by Tetrax-10** [comment]
> Not entirely sure if this is the expected behaviour or not, if it is then an option to disable this in settings would be great as it's the only thing letting down a really good theme.

Thats its behaviour. if i have time i will make a option to disable it

**Comment by Tetrax-10** [comment]
> I'm having the same issue, but it has been happening ever since i'v install the theme (via marketplace). I tried installing the theme again from the github but nothing.

You have 1.1.84, Update Spotify to 1.1.99
This is the latest version on linux and nord spotify supports it

**Comment by RickyChan21** [comment]
Hello, is there a option to disable this behavior? I want to disable having to scroll each time you enter a playlist

**Comment by Tetrax-10** [comment]
Like disabling that big banners? Yeah currently that option is under development
